#ifndef __KEYCODE_H__
#define __KEYCODE_H__

#ifndef _WIN32
    #include <X11/Xlib.h>
    #include <X11/Xutil.h>      /* BitmapOpenFailed, etc.    */
    #include <X11/cursorfont.h> /* pre-defined crusor shapes */
    #include <linux/input.h>
#endif
#include <SDL2/SDL.h>

#include "base.h"
#include "rbtree.h"
#include "keycode.h"

#ifdef _WIN32

struct keycode{
    	uint32_t key;
		uint32_t value;
        struct rb_node rb_node;    
    } keybd_key[] = { 
	{ SDLK_RETURN , VK_RETURN},
	{ SDLK_ESCAPE , VK_ESCAPE},
	{ SDLK_BACKSPACE , VK_BACK},
	{ SDLK_TAB , VK_TAB},
	{ SDLK_SPACE , VK_SPACE},
	//{ SDLK_EXCLAIM , '!'},
	//{ SDLK_QUOTEDBL , '"'},
	//{ SDLK_HASH , '#'},
	//{ SDLK_PERCENT , '%'},
	//{ SDLK_DOLLAR , '$'},
	//{ SDLK_AMPERSAND , '&'},
	{ SDLK_QUOTE , VK_OEM_5},
	//{ SDLK_LEFTPAREN , '('},
	//{ SDLK_RIGHTPAREN , ')'},
	//{ SDLK_ASTERISK , '*'},
	{ SDLK_PLUS , VK_OEM_PLUS},
	{ SDLK_COMMA , VK_OEM_COMMA},
	{ SDLK_MINUS , VK_OEM_MINUS},
	{ SDLK_PERIOD , VK_OEM_PERIOD},
	{ SDLK_SLASH , VK_OEM_2},
	{ SDLK_0 , 0x30},
	{ SDLK_1 , 0x31},
	{ SDLK_2 , 0x32},
	{ SDLK_3 , 0x33},
	{ SDLK_4 , 0x34},
	{ SDLK_5 , 0x35},
	{ SDLK_6 , 0x36},
	{ SDLK_7 , 0x37},
	{ SDLK_8 , 0x38},
	{ SDLK_9 , 0x39},
#if 0
	{ SDLK_COLON , XK_colon},
	{ SDLK_SEMICOLON , XK_semicolon},
	{ SDLK_LESS , XK_less},
	{ SDLK_EQUALS , XK_equal},
	{ SDLK_GREATER , XK_greater},
	{ SDLK_QUESTION , XK_question},
	{ SDLK_AT , XK_at},
#endif
	 /*
	    Skip uppercase letters},
	  */
	{ SDLK_LEFTBRACKET , VK_OEM_4},
	{ SDLK_BACKSLASH , VK_OEM_5},
	{ SDLK_RIGHTBRACKET , VK_OEM_6},
	//{ SDLK_CARET , '^'},
	//{ SDLK_UNDERSCORE , '_'},
	{ SDLK_BACKQUOTE , 'VK_OEM_3'},
	{ SDLK_a , 0x41},
	{ SDLK_b , 0x42},
	{ SDLK_c , 0x43},
	{ SDLK_d , 0x44},
	{ SDLK_e , 0x45},
	{ SDLK_f , 0x46},
	{ SDLK_g , 0x47},
	{ SDLK_h , 0x48},
	{ SDLK_i , 0x49},
	{ SDLK_j , 0x4a},
	{ SDLK_k , 0x4b},
	{ SDLK_l , 0x4c},
	{ SDLK_m , 0x4d},
	{ SDLK_n , 0x4e},
	{ SDLK_o , 0x4f},
	{ SDLK_p , 0x50},
	{ SDLK_q , 0x51},
	{ SDLK_r , 0x52},
	{ SDLK_s , 0x53},
	{ SDLK_t , 0x54},
	{ SDLK_u , 0x55},
	{ SDLK_v , 0x56},
	{ SDLK_w , 0x57},
	{ SDLK_x , 0x58},
	{ SDLK_y , 0x59},
	{ SDLK_z , 0x5a},
	 
	{ SDLK_CAPSLOCK , VK_CAPITAL},
	 
	{ SDLK_F1 , VK_F1},
	{ SDLK_F2 , VK_F2},
	{ SDLK_F3 , VK_F3},
	{ SDLK_F4 , VK_F4},
	{ SDLK_F5 , VK_F5},
	{ SDLK_F6 , VK_F6},
	{ SDLK_F7 , VK_F7},
	{ SDLK_F8 , VK_F8},
	{ SDLK_F9 , VK_F9},
	{ SDLK_F10 , VK_F10},
	{ SDLK_F11 , VK_F11},
	{ SDLK_F12 , VK_F12},
	 
	//{ SDLK_PRINTSCREEN , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PRINTSCREEN)},
	{ SDLK_SCROLLLOCK , VK_SNAPSHOT},
	{ SDLK_PAUSE , VK_PAUSE},
	{ SDLK_INSERT , VK_INSERT},
	{ SDLK_HOME , VK_HOME},
	{ SDLK_PAGEUP , VK_PRIOR},
	{ SDLK_DELETE , VK_DELETE},
	{ SDLK_END , VK_END},
	{ SDLK_PAGEDOWN , VK_NEXT},
	{ SDLK_RIGHT , VK_RIGHT},
	{ SDLK_LEFT , VK_LEFT},
	{ SDLK_DOWN , VK_DOWN},
	{ SDLK_UP , VK_UP},
	 
	//{ SDLK_NUMLOCKCLEAR , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_NUMLOCKCLEAR)},
	//{ SDLK_KP_DIVIDE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DIVIDE)},
	//{ SDLK_KP_MULTIPLY , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MULTIPLY)},
	//{ SDLK_KP_MINUS , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MINUS)},
	//{ SDLK_KP_PLUS , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUS)},
	{ SDLK_KP_ENTER , VK_RETURN},
	{ SDLK_KP_1 , VK_NUMPAD1},
	{ SDLK_KP_2 , VK_NUMPAD2},
	{ SDLK_KP_3 , VK_NUMPAD3},
	{ SDLK_KP_4 , VK_NUMPAD4},
	{ SDLK_KP_5 , VK_NUMPAD5},
	{ SDLK_KP_6 , VK_NUMPAD6},
	{ SDLK_KP_7 , VK_NUMPAD7},
	{ SDLK_KP_8 , VK_NUMPAD8},
	{ SDLK_KP_9 , VK_NUMPAD9},
	{ SDLK_KP_0 , VK_NUMPAD0},
	//{ SDLK_KP_PERIOD , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERIOD)},
	 
	//{ SDLK_APPLICATION , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_APPLICATION)},
	//{ SDLK_POWER , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_POWER)},
	//{ SDLK_KP_EQUALS , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALS)},
	{ SDLK_F13 , VK_F13},
	{ SDLK_F14 , VK_F14},
	{ SDLK_F15 , VK_F15},
	{ SDLK_F16 , VK_F16},
	{ SDLK_F17 , VK_F17},
	{ SDLK_F18 , VK_F18},
	{ SDLK_F19 , VK_F19},
	{ SDLK_F20 , VK_F20},
	{ SDLK_F21 , VK_F21},
	{ SDLK_F22 , VK_F22},
	{ SDLK_F23 , VK_F23},
	{ SDLK_F24 , VK_F24},
	{ SDLK_EXECUTE , VK_EXECUTE},
	{ SDLK_HELP , VK_HELP},
	{ SDLK_MENU , VK_MENU},
	{ SDLK_SELECT , VK_SELECT},
	//{ SDLK_STOP , },
	//{ SDLK_AGAIN , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AGAIN)},
	//{ SDLK_UNDO , XK_Undo},
	//{ SDLK_CUT , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CUT)},
	//{ SDLK_COPY , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_COPY)},
	//{ SDLK_PASTE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PASTE)},
	//{ SDLK_FIND , XK_Find},
	//{ SDLK_MUTE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MUTE)},
	//{ SDLK_VOLUMEUP , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEUP)},
	//{ SDLK_VOLUMEDOWN , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEDOWN)},
	//{ SDLK_KP_COMMA , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COMMA)},
	//{ SDLK_KP_EQUALSAS400 },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALSAS400)},
	 
	//{ SDLK_ALTERASE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_ALTERASE)},
	//{ SDLK_SYSREQ , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SYSREQ)},
	{ SDLK_CANCEL , VK_CANCEL},
	{ SDLK_CLEAR , VK_CLEAR},
	{ SDLK_PRIOR , VK_PRIOR},
	//{ SDLK_RETURN2 , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RETURN2)},
	{ SDLK_SEPARATOR , VK_SEPARATOR},
	//{ SDLK_OUT , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OUT)},
	//{ SDLK_OPER , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OPER)},
	//{ SDLK_CLEARAGAIN , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CLEARAGAIN)},
	//{ SDLK_CRSEL , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CRSEL)},
	//{ SDLK_EXSEL , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EXSEL)},
	 
	//{ SDLK_KP_00 , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_00)},
	//{ SDLK_KP_000 , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_000)},
	//{ SDLK_THOUSANDSSEPARATOR },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_THOUSANDSSEPARATOR)},
	//{ SDLK_DECIMALSEPARATOR },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DECIMALSEPARATOR)},
	//{ SDLK_CURRENCYUNIT , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYUNIT)},
	//{ SDLK_CURRENCYSUBUNIT },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYSUBUNIT)},
	//{ SDLK_KP_LEFTPAREN , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTPAREN)},
	//{ SDLK_KP_RIGHTPAREN , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTPAREN)},
	//{ SDLK_KP_LEFTBRACE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTBRACE)},
	//{ SDLK_KP_RIGHTBRACE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTBRACE)},
	{ SDLK_KP_TAB , VK_TAB},
	//{ SDLK_KP_BACKSPACE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BACKSPACE)},
	//{ SDLK_KP_A , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_A)},
	//{ SDLK_KP_B , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_B)},
	//{ SDLK_KP_C , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_C)},
	//{ SDLK_KP_D , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_D)},
	//{ SDLK_KP_E , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_E)},
	//{ SDLK_KP_F , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_F)},
	//{ SDLK_KP_XOR , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_XOR)},
	//{ SDLK_KP_POWER , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_POWER)},
	//{ SDLK_KP_PERCENT , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERCENT)},
	//{ SDLK_KP_LESS , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LESS)},
	//{ SDLK_KP_GREATER , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_GREATER)},
	//{ SDLK_KP_AMPERSAND , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AMPERSAND)},
	//{ SDLK_KP_DBLAMPERSAND },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DBLAMPERSAND)},
	//{ SDLK_KP_VERTICALBAR },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_VERTICALBAR)},
	//{ SDLK_KP_DBLVERTICALBAR },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DBLVERTICALBAR)},
	//{ SDLK_KP_COLON , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COLON)},
	//{ SDLK_KP_HASH , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HASH)},
	//{ SDLK_KP_SPACE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_SPACE)},
	//{ SDLK_KP_AT , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AT)},
	//{ SDLK_KP_EXCLAM , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EXCLAM)},
	//{ SDLK_KP_MEMSTORE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSTORE)},
	//{ SDLK_KP_MEMRECALL , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMRECALL)},
	//{ SDLK_KP_MEMCLEAR , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMCLEAR)},
	//{ SDLK_KP_MEMADD , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMADD)},
	//{ SDLK_KP_MEMSUBTRACT },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSUBTRACT)},
	//{ SDLK_KP_MEMMULTIPLY },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMMULTIPLY)},
	//{ SDLK_KP_MEMDIVIDE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMDIVIDE)},
	//{ SDLK_KP_PLUSMINUS , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUSMINUS)},
	//{ SDLK_KP_CLEAR , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEAR)},
	//{ SDLK_KP_CLEARENTRY , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEARENTRY)},
	//{ SDLK_KP_BINARY , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BINARY)},
	//{ SDLK_KP_OCTAL , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_OCTAL)},
	//{ SDLK_KP_DECIMAL , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DECIMAL)},
	//{ SDLK_KP_HEXADECIMAL },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HEXADECIMAL)},
	 
	{ SDLK_LCTRL , VK_CONTROL},
	{ SDLK_LSHIFT , VK_SHIFT},
	{ SDLK_LALT , VK_MENU},
	{ SDLK_LGUI , VK_LWIN},
	{ SDLK_RCTRL , VK_CONTROL},
	{ SDLK_RSHIFT , VK_SHIFT},
	{ SDLK_RALT , VK_MENU},
	{ SDLK_RGUI , VK_RWIN},
	 
	//{ SDLK_MODE , XK_Mode_switch},
	 
	//{ SDLK_AUDIONEXT , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIONEXT)},
	//{ SDLK_AUDIOPREV , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOPREV)},
	//{ SDLK_AUDIOSTOP , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOSTOP)},
	//{ SDLK_AUDIOPLAY , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOPLAY)},
	//{ SDLK_AUDIOMUTE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOMUTE)},
	//{ SDLK_MEDIASELECT , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIASELECT)},
	//{ SDLK_WWW , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_WWW)},
	//{ SDLK_MAIL , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MAIL)},
	//{ SDLK_CALCULATOR , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CALCULATOR)},
	//{ SDLK_COMPUTER , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_COMPUTER)},
	//{ SDLK_AC_SEARCH , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_SEARCH)},
	//{ SDLK_AC_HOME , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_HOME)},
	//{ SDLK_AC_BACK , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BACK)},
	//{ SDLK_AC_FORWARD , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_FORWARD)},
	//{ SDLK_AC_STOP , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_STOP)},
	//{ SDLK_AC_REFRESH , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_REFRESH)},
	//{ SDLK_AC_BOOKMARKS , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BOOKMARKS)},
	 
	//{ SDLK_BRIGHTNESSDOWN },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_BRIGHTNESSDOWN)},
	//{ SDLK_BRIGHTNESSUP , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_BRIGHTNESSUP)},
	//{ SDLK_DISPLAYSWITCH , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DISPLAYSWITCH)},
	//{ SDLK_KBDILLUMTOGGLE },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KBDILLUMTOGGLE)},
	//{ SDLK_KBDILLUMDOWN , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KBDILLUMDOWN)},
	//{ SDLK_KBDILLUMUP , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KBDILLUMUP)},
	//{ SDLK_EJECT , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EJECT)},
	//{ SDLK_SLEEP , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SLEEP)},
	//{ SDLK_APP1 , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_APP1)},
	//{ SDLK_APP2 , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_APP2)},
	 
	//{ SDLK_AUDIOREWIND , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOREWIND)},
	//{ SDLK_AUDIOFASTFORWARD , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOFASTFORWARD)},
	{ SDLK_UNKNOWN, -1}
};


#else

struct keycode{
    	uint32_t key;
		uint32_t value;
        struct rb_node rb_node;    
    } keybd_key[] = { 

	{ SDLK_RETURN , XK_Return},
	{ SDLK_ESCAPE , XK_Escape},
	{ SDLK_BACKSPACE , XK_BackSpace},
	{ SDLK_TAB , XK_Tab},
	{ SDLK_SPACE , XK_KP_Space},
	//{ SDLK_EXCLAIM , '!'},
	//{ SDLK_QUOTEDBL , XK_quotedbl},
	//{ SDLK_HASH , '#'},
	//{ SDLK_PERCENT , '%'},
	//{ SDLK_DOLLAR , '$'},
	//{ SDLK_AMPERSAND , '&'},
	{ SDLK_QUOTE , XK_quotedbl},
	//{ SDLK_LEFTPAREN , '('},
	//{ SDLK_RIGHTPAREN , ')'},
	//{ SDLK_ASTERISK , '*'},
	//{ SDLK_PLUS , '+'},
	{ SDLK_COMMA , XK_comma},
	{ SDLK_MINUS , XK_minus},
	{ SDLK_PERIOD , XK_period},
	{ SDLK_SLASH , XK_slash},
	{ SDLK_0 , XK_0},
	{ SDLK_1 , XK_1},
	{ SDLK_2 , XK_2},
	{ SDLK_3 , XK_3},
	{ SDLK_4 , XK_4},
	{ SDLK_5 , XK_5},
	{ SDLK_6 , XK_6},
	{ SDLK_7 , XK_7},
	{ SDLK_8 , XK_8},
	{ SDLK_9 , XK_9},
	{ SDLK_COLON , XK_colon},
	{ SDLK_SEMICOLON , XK_semicolon},
	{ SDLK_LESS , XK_less},
	{ SDLK_EQUALS , XK_equal},
	{ SDLK_GREATER , XK_greater},
	{ SDLK_QUESTION , XK_question},
	{ SDLK_AT , XK_at},
	 /*
	    Skip uppercase letters},
	  */
	{ SDLK_LEFTBRACKET , XK_braceleft},
	{ SDLK_BACKSLASH , XK_bar},
	{ SDLK_RIGHTBRACKET , XK_braceright},
	//{ SDLK_CARET , '^'},
	//{ SDLK_UNDERSCORE , '_'},
	{ SDLK_BACKQUOTE , XK_asciitilde},
	{ SDLK_a , XK_a},
	{ SDLK_b , XK_b},
	{ SDLK_c , XK_c},
	{ SDLK_d , XK_d},
	{ SDLK_e , XK_e},
	{ SDLK_f , XK_f},
	{ SDLK_g , XK_g},
	{ SDLK_h , XK_h},
	{ SDLK_i , XK_i},
	{ SDLK_j , XK_j},
	{ SDLK_k , XK_k},
	{ SDLK_l , XK_l},
	{ SDLK_m , XK_m},
	{ SDLK_n , XK_n},
	{ SDLK_o , XK_o},
	{ SDLK_p , XK_p},
	{ SDLK_q , XK_q},
	{ SDLK_r , XK_r},
	{ SDLK_s , XK_s},
	{ SDLK_t , XK_t},
	{ SDLK_u , XK_u},
	{ SDLK_v , XK_v},
	{ SDLK_w , XK_w},
	{ SDLK_x , XK_x},
	{ SDLK_y , XK_y},
	{ SDLK_z , XK_z},
	 
	{ SDLK_CAPSLOCK , XK_Caps_Lock},
	 
	{ SDLK_F1 , XK_F1},
	{ SDLK_F2 , XK_F2},
	{ SDLK_F3 , XK_F3},
	{ SDLK_F4 , XK_F4},
	{ SDLK_F5 , XK_F5},
	{ SDLK_F6 , XK_F6},
	{ SDLK_F7 , XK_F7},
	{ SDLK_F8 , XK_F8},
	{ SDLK_F9 , XK_F9},
	{ SDLK_F10 , XK_F10},
	{ SDLK_F11 , XK_F11},
	{ SDLK_F12 , XK_F12},
	 
	//{ SDLK_PRINTSCREEN , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PRINTSCREEN)},
	{ SDLK_SCROLLLOCK , XK_Scroll_Lock},
	{ SDLK_PAUSE , XK_Pause},
	{ SDLK_INSERT , XK_Insert},
	{ SDLK_HOME , XK_Home},
	{ SDLK_PAGEUP , XK_Page_Up},
	{ SDLK_DELETE , XK_Delete},
	{ SDLK_END , XK_End},
	{ SDLK_PAGEDOWN , XK_Page_Down},
	{ SDLK_RIGHT , XK_Right},
	{ SDLK_LEFT , XK_Left},
	{ SDLK_DOWN , XK_Down},
	{ SDLK_UP , XK_Up},
	 
	//{ SDLK_NUMLOCKCLEAR , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_NUMLOCKCLEAR)},
	//{ SDLK_KP_DIVIDE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DIVIDE)},
	//{ SDLK_KP_MULTIPLY , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MULTIPLY)},
	//{ SDLK_KP_MINUS , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MINUS)},
	//{ SDLK_KP_PLUS , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUS)},
	{ SDLK_KP_ENTER , XK_KP_Enter},
	{ SDLK_KP_1 , XK_KP_1},
	{ SDLK_KP_2 , XK_KP_2},
	{ SDLK_KP_3 , XK_KP_3},
	{ SDLK_KP_4 , XK_KP_4},
	{ SDLK_KP_5 , XK_KP_5},
	{ SDLK_KP_6 , XK_KP_6},
	{ SDLK_KP_7 , XK_KP_7},
	{ SDLK_KP_8 , XK_KP_8},
	{ SDLK_KP_9 , XK_KP_9},
	{ SDLK_KP_0 , XK_KP_0},
	//{ SDLK_KP_PERIOD , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERIOD)},
	 
	//{ SDLK_APPLICATION , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_APPLICATION)},
	//{ SDLK_POWER , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_POWER)},
	//{ SDLK_KP_EQUALS , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALS)},
	{ SDLK_F13 , XK_F13},
	{ SDLK_F14 , XK_F14},
	{ SDLK_F15 , XK_F15},
	{ SDLK_F16 , XK_F16},
	{ SDLK_F17 , XK_F17},
	{ SDLK_F18 , XK_F18},
	{ SDLK_F19 , XK_F19},
	{ SDLK_F20 , XK_F20},
	{ SDLK_F21 , XK_F21},
	{ SDLK_F22 , XK_F22},
	{ SDLK_F23 , XK_F23},
	{ SDLK_F24 , XK_F24},
	{ SDLK_EXECUTE , XK_Execute},
	{ SDLK_HELP , XK_Help},
	{ SDLK_MENU , XK_Menu},
	{ SDLK_SELECT , XK_Select},
	//{ SDLK_STOP , },
	//{ SDLK_AGAIN , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AGAIN)},
	{ SDLK_UNDO , XK_Undo},
	//{ SDLK_CUT , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CUT)},
	//{ SDLK_COPY , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_COPY)},
	//{ SDLK_PASTE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PASTE)},
	{ SDLK_FIND , XK_Find},
	//{ SDLK_MUTE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MUTE)},
	//{ SDLK_VOLUMEUP , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEUP)},
	//{ SDLK_VOLUMEDOWN , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEDOWN)},
	//{ SDLK_KP_COMMA , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COMMA)},
	//{ SDLK_KP_EQUALSAS400 },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALSAS400)},
	 
	//{ SDLK_ALTERASE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_ALTERASE)},
	//{ SDLK_SYSREQ , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SYSREQ)},
	{ SDLK_CANCEL , XK_Cancel},
	{ SDLK_CLEAR , XK_Clear},
	{ SDLK_PRIOR , XK_Prior},
	//{ SDLK_RETURN2 , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RETURN2)},
	{ SDLK_SEPARATOR , XK_KP_Separator},
	//{ SDLK_OUT , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OUT)},
	//{ SDLK_OPER , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OPER)},
	//{ SDLK_CLEARAGAIN , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CLEARAGAIN)},
	//{ SDLK_CRSEL , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CRSEL)},
	//{ SDLK_EXSEL , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EXSEL)},
	 
	//{ SDLK_KP_00 , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_00)},
	//{ SDLK_KP_000 , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_000)},
	//{ SDLK_THOUSANDSSEPARATOR },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_THOUSANDSSEPARATOR)},
	//{ SDLK_DECIMALSEPARATOR },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DECIMALSEPARATOR)},
	//{ SDLK_CURRENCYUNIT , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYUNIT)},
	//{ SDLK_CURRENCYSUBUNIT },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYSUBUNIT)},
	//{ SDLK_KP_LEFTPAREN , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTPAREN)},
	//{ SDLK_KP_RIGHTPAREN , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTPAREN)},
	//{ SDLK_KP_LEFTBRACE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTBRACE)},
	//{ SDLK_KP_RIGHTBRACE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTBRACE)},
	{ SDLK_KP_TAB , XK_KP_Tab},
	//{ SDLK_KP_BACKSPACE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BACKSPACE)},
	//{ SDLK_KP_A , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_A)},
	//{ SDLK_KP_B , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_B)},
	//{ SDLK_KP_C , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_C)},
	//{ SDLK_KP_D , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_D)},
	//{ SDLK_KP_E , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_E)},
	//{ SDLK_KP_F , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_F)},
	//{ SDLK_KP_XOR , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_XOR)},
	//{ SDLK_KP_POWER , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_POWER)},
	//{ SDLK_KP_PERCENT , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERCENT)},
	//{ SDLK_KP_LESS , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LESS)},
	//{ SDLK_KP_GREATER , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_GREATER)},
	//{ SDLK_KP_AMPERSAND , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AMPERSAND)},
	//{ SDLK_KP_DBLAMPERSAND },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DBLAMPERSAND)},
	//{ SDLK_KP_VERTICALBAR },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_VERTICALBAR)},
	//{ SDLK_KP_DBLVERTICALBAR },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DBLVERTICALBAR)},
	//{ SDLK_KP_COLON , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COLON)},
	//{ SDLK_KP_HASH , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HASH)},
	//{ SDLK_KP_SPACE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_SPACE)},
	//{ SDLK_KP_AT , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AT)},
	//{ SDLK_KP_EXCLAM , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EXCLAM)},
	//{ SDLK_KP_MEMSTORE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSTORE)},
	//{ SDLK_KP_MEMRECALL , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMRECALL)},
	//{ SDLK_KP_MEMCLEAR , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMCLEAR)},
	//{ SDLK_KP_MEMADD , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMADD)},
	//{ SDLK_KP_MEMSUBTRACT },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSUBTRACT)},
	//{ SDLK_KP_MEMMULTIPLY },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMMULTIPLY)},
	//{ SDLK_KP_MEMDIVIDE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMDIVIDE)},
	//{ SDLK_KP_PLUSMINUS , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUSMINUS)},
	//{ SDLK_KP_CLEAR , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEAR)},
	//{ SDLK_KP_CLEARENTRY , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEARENTRY)},
	//{ SDLK_KP_BINARY , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BINARY)},
	//{ SDLK_KP_OCTAL , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_OCTAL)},
	//{ SDLK_KP_DECIMAL , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DECIMAL)},
	//{ SDLK_KP_HEXADECIMAL },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HEXADECIMAL)},
	 
	{ SDLK_LCTRL , XK_Control_L},
	{ SDLK_LSHIFT , XK_Shift_L},
	{ SDLK_LALT , XK_Alt_L},
	{ SDLK_LGUI , XK_Meta_L},
	{ SDLK_RCTRL , XK_Control_R},
	{ SDLK_RSHIFT , XK_Shift_R},
	{ SDLK_RALT , XK_Alt_R},
	{ SDLK_RGUI , XK_Meta_R},
	 
	{ SDLK_MODE , XK_Mode_switch},
	 
	//{ SDLK_AUDIONEXT , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIONEXT)},
	//{ SDLK_AUDIOPREV , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOPREV)},
	//{ SDLK_AUDIOSTOP , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOSTOP)},
	//{ SDLK_AUDIOPLAY , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOPLAY)},
	//{ SDLK_AUDIOMUTE , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOMUTE)},
	//{ SDLK_MEDIASELECT , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIASELECT)},
	//{ SDLK_WWW , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_WWW)},
	//{ SDLK_MAIL , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MAIL)},
	//{ SDLK_CALCULATOR , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CALCULATOR)},
	//{ SDLK_COMPUTER , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_COMPUTER)},
	//{ SDLK_AC_SEARCH , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_SEARCH)},
	//{ SDLK_AC_HOME , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_HOME)},
	//{ SDLK_AC_BACK , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BACK)},
	//{ SDLK_AC_FORWARD , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_FORWARD)},
	//{ SDLK_AC_STOP , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_STOP)},
	//{ SDLK_AC_REFRESH , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_REFRESH)},
	//{ SDLK_AC_BOOKMARKS , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BOOKMARKS)},
	 
	//{ SDLK_BRIGHTNESSDOWN },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_BRIGHTNESSDOWN)},
	//{ SDLK_BRIGHTNESSUP , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_BRIGHTNESSUP)},
	//{ SDLK_DISPLAYSWITCH , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DISPLAYSWITCH)},
	//{ SDLK_KBDILLUMTOGGLE },
	//{     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KBDILLUMTOGGLE)},
	//{ SDLK_KBDILLUMDOWN , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KBDILLUMDOWN)},
	//{ SDLK_KBDILLUMUP , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KBDILLUMUP)},
	//{ SDLK_EJECT , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EJECT)},
	//{ SDLK_SLEEP , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SLEEP)},
	//{ SDLK_APP1 , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_APP1)},
	//{ SDLK_APP2 , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_APP2)},
	 
	//{ SDLK_AUDIOREWIND , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOREWIND)},
	//{ SDLK_AUDIOFASTFORWARD , SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOFASTFORWARD)},
	{ SDLK_UNKNOWN, -1}

    };  
#endif //_WIN32

static struct rb_root root = RB_ROOT;
int set_keycode(uint32_t key, struct keycode *code)
{   
    if(!code)
        return ERROR;
    
    struct rb_node **tmp = &(root.rb_node), *parent = NULL;
    
    /* Figure out where to put new node */
    while (*tmp)
    {   
        struct keycode * my = container_of(*tmp, struct keycode, rb_node);
        parent = *tmp;
        if (key < my->key)
            tmp = &((*tmp)->rb_left);
        else if (key > my->key)
            tmp = &((*tmp)->rb_right);
        else
        {   
            return ERROR;
        }
    }   
    code->key = key;
    /* Add new node and rebalance tree. */
    rb_link_node(&code->rb_node, parent, tmp);
    rb_insert_color(&code->rb_node, &root);
    return SUCCESS;
}

struct keycode *get_keycode(uint32_t key)
{
    struct keycode* code = NULL;
    
    struct rb_node *rbnode = root.rb_node;
    struct keycode *mynode;
    
    while (rbnode!=NULL)
    {   
        mynode = container_of(rbnode, struct keycode, rb_node);
    
        if (key < mynode->key)
            rbnode = rbnode->rb_left;
        else if (key > mynode->key)
            rbnode = rbnode->rb_right;
        else
        {   
            code = mynode;
            break;
        }   
    }   
    return code;
}

#endif //__KEYCODE_H__



